export const HITS_LIST_REQUEST = 'HITS_LIST_REQUEST';
export const HITS_LIST_FAILTURE = 'HITS_LIST_FAILTURE';
export const HITS_LIST_SUCCESS = 'HITS_LIST_SUCCESS';

export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_FAILTURE = 'CATEGORIES_FAILTURE';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_CHANGE = 'CATEGORIES_CHANGE';

export const ITEMS_REQUEST = 'ITEMS_REQUEST';
export const ITEMS_FAILTURE = 'ITEMS_FAILTURE';
export const ITEMS_SUCCESS = 'ITEMS_SUCCESS';

export const ITEM_REQUEST = 'ITEM_REQUEST';
export const ITEM_FAILTURE = 'ITEM_FAILTURE';
export const ITEM_SUCCESS = 'ITEM_SUCCESS';

export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const CLEAR_LIST = 'CLEAR_LIST';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const SEND_CART_REQUEST = 'SEND_CART_REQUEST';
export const SEND_CART_SUCCESS = 'SEND_CART_SUCCESS';
export const SEND_CART_FAILTURE = 'SEND_CART_FAILTURE';