export const HITS_LIST_REQUEST = 'HITS_LIST_REQUEST';
export const HITS_LIST_FAILTURE = 'HITS_LIST_FAILTURE';
export const HITS_LIST_SUCCESS = 'HITS_LIST_SUCCESS';

export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_FAILTURE = 'CATEGORIES_FAILTURE';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';

export const ITEMS_REQUEST = 'ITEMS_REQUEST';
export const ITEMS_FAILTURE = 'ITEMS_FAILTURE';
export const ITEMS_SUCCESS = 'ITEMS_SUCCESS';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_FAILTURE = 'SEARCH_FAILTURE';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
